/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import com.google.gson.Gson;
import java.io.FileWriter;
import java.io.FileReader;
import java.io.IOException;


class Persona {


    String nombre;
    int edad;

    Persona(String nombre, int edad){
        this.nombre = nombre;
        this.edad = edad;
    }
    // Constructor vacío requerido por Gson para deserializar
    Persona() {}
}

public class App {

    public static void main(String[] args){

        Persona yo = new Persona("Emiliano", 19);
        Gson gson = new Gson();
        
        // Serialización
        String json = gson.toJson(yo);
        
        // Guardar en archivo
        System.out.println("JSON generado:");
        System.out.println(json);

        try(FileWriter writer = new FileWriter("persona.json")){
            writer.write(json);
            System.out.println("JSON guardado en \"persona.json\"");
        } catch (IOException e){
            e.printStackTrace();
        }

        // Deserialización
        Persona copia = gson.fromJson(json, Persona.class);
       
        try(FileReader reader = new FileReader("persona.json")){
            Persona desdeArchivo = gson.fromJson(reader, Persona.class);
            System.out.println("Objeto deserializado: ");
            System.out.println("Nombre: " + desdeArchivo.nombre);
            System.out.println("Edad: " + desdeArchivo.edad);
        } catch (IOException e){
            e.printStackTrace();
        }
    }
}
